package e2e

import (
	"context"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/Kocoro-lab/ShanClaw/internal/client"
)

// TestAuthLive_RegisterAndUnverifiedLogin is a live smoke test against
// the configured Cloud (default https://api-dev.shannon.run or
// SHANNON_E2E_AUTH_ENDPOINT). Gated by SHANNON_E2E_LIVE=1 so CI skips it.
//
// Coverage:
//  1. Register a fresh email → 202 + verification_sent
//  2. Login the same email → 403 email_not_verified (account not yet verified)
//  3. Resend verification → 200
//
// We deliberately do NOT verify the email or complete login, because that
// requires clicking a link in real mail and would either need an inbox
// integration or pre-arranged test accounts. The two pre-verification
// branches are enough to confirm the daemon ↔ Cloud contract.
//
// Cleanup: Cloud has no public account-delete; the orphan account stays
// in dev. We use a deterministic prefix so we can sweep manually if
// needed (`kocoro-e2e-*@example.test`).
func TestAuthLive_RegisterAndUnverifiedLogin(t *testing.T) {
	if os.Getenv("SHANNON_E2E_LIVE") != "1" {
		t.Skip("set SHANNON_E2E_LIVE=1 to run live Cloud auth tests")
	}

	endpoint := os.Getenv("SHANNON_E2E_AUTH_ENDPOINT")
	if endpoint == "" {
		endpoint = "https://api-dev.shannon.run"
	}

	authClient := client.NewAuthClient(endpoint, nil)
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	// Deterministic-prefix unique email so successive runs don't collide
	// and orphan accounts can be swept by prefix on the Cloud side.
	email := fmt.Sprintf("kocoro-e2e-%d@example.test", time.Now().UnixNano())
	password := "Pw1Pw1Pw1Pw1!" // meets >=8 chars policy

	// 1) Register — provider + username are required by Cloud; the
	// live test sets them explicitly because it calls AuthClient
	// directly (not via AuthManager which would derive a username).
	if err := authClient.Register(ctx, client.AuthRegisterRequest{
		Provider: client.ProviderEmail,
		Email:    email,
		Username: fmt.Sprintf("e2e_%d", time.Now().UnixNano()%1_000_000_000),
		Password: password,
		FullName: "E2E Test",
	}); err != nil {
		// Cloud may reject if account already exists from a prior run (unique
		// suffix should prevent this, but rate-limit can also surface).
		if ae, ok := client.IsAuthError(err); ok && (ae.Code == "email_taken" || ae.Code == "rate_limited") {
			t.Skipf("register skipped due to Cloud state: %v", ae)
		}
		t.Fatalf("Register live: %v", err)
	}

	// 2) Login (expect 403 email_not_verified)
	_, err := authClient.Login(ctx, client.AuthLoginRequest{Email: email, Password: password})
	if err == nil {
		t.Fatal("Login should fail for unverified account")
	}
	ae, ok := client.IsAuthError(err)
	if !ok {
		t.Fatalf("expected AuthError, got %v", err)
	}
	if ae.Code != "email_not_verified" {
		t.Fatalf("Login on unverified account: expected email_not_verified, got code=%q HTTPCode=%d", ae.Code, ae.HTTPCode)
	}

	// 3) Resend verification — Cloud always returns 200 (anti-enumeration).
	if err := authClient.ResendVerification(ctx, email, ""); err != nil {
		// Rate-limited resend is acceptable.
		if ae, ok := client.IsAuthError(err); ok && ae.Code == "rate_limited" {
			t.Logf("resend rate-limited (ok): %v", ae)
		} else {
			t.Fatalf("ResendVerification: %v", err)
		}
	}
}

// TestAuthLive_ForgotPassword_AlwaysOK exercises the anti-enumeration
// /forgot-password endpoint with a known-nonexistent email. Cloud must
// still return 200.
func TestAuthLive_ForgotPassword_AlwaysOK(t *testing.T) {
	if os.Getenv("SHANNON_E2E_LIVE") != "1" {
		t.Skip("set SHANNON_E2E_LIVE=1 to run live Cloud auth tests")
	}
	endpoint := os.Getenv("SHANNON_E2E_AUTH_ENDPOINT")
	if endpoint == "" {
		endpoint = "https://api-dev.shannon.run"
	}
	authClient := client.NewAuthClient(endpoint, nil)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	email := fmt.Sprintf("kocoro-e2e-does-not-exist-%d@example.test", time.Now().UnixNano())
	if err := authClient.ForgotPassword(ctx, email, ""); err != nil {
		if ae, ok := client.IsAuthError(err); ok && ae.Code == "rate_limited" {
			t.Skipf("forgot-password rate-limited: %v", ae)
		}
		t.Fatalf("ForgotPassword live: %v", err)
	}
}

// Compile-time guard: make sure strings is exercised so linters do not
// flag the import as unused on builds that skip the SHANNON_E2E_LIVE
// branches above. (The import is needed when the file is generated by
// tooling that adds string-handling for the verification token sweep.)
var _ = strings.TrimSpace
